final products = [
  {
  'id': '0',
  'category': 'Judogi',
  'title': 'White Judogi Taisho IJF - KuSakura',
  'price': '\$ 949,00',
  'sizes': ['A1', 'A2', 'A3', 'A4'],
  'imageUrl': 'assets/images/judogi.png',
  },
  {
  'id': '1',
  'category': 'Obi',
  'title': 'Black Belt Official Kodokan - KuSakura',
  'price': '\$ 89,00',
  'sizes': ['1', '2', '3', '4'],
  'imageUrl': 'assets/images/obi.png',
  },
  {
  'id': '2',
  'category': 'Rashguard',
  'title': 'Competition Rashguard CBJ - KuSakura',
  'price': '\$ 49,00',
  'sizes': ['A1', 'A2', 'A3', 'A4'],
  'imageUrl': 'assets/images/rashguard.png',
  },
  {
  'id': '3',
  'category': 'Accessories',
  'title': 'Black Sliders - KuSakura',
  'price': '\$ 29,00',
  'sizes': ['41', '42', '43', '44', '46'],
  'imageUrl': 'assets/images/surippa.png',
  },
  {
  'id': '4',
  'category': 'Obi',
  'title': 'Black Belt - Mizuno',
  'price': '\$ 59,00',
  'sizes': ['1', '2', '3', '4'],
  'imageUrl': 'assets/images/black_mizuno.png',
  },
  {
  'id': '5',
  'category': 'Judogi',
  'title': 'White Judogi - Adidas',
  'price': '\$ 529,00',
  'sizes': ['A1', 'A2', 'A3', 'A4'],
  'imageUrl': 'assets/images/judogi_adidas.png',
  },
  {
  'id': '6',
  'category': 'Accessories',
  'title': 'CBJ Judo Suitcase',
  'price': '\$ 99,00',
  'sizes': ['White'],
  'imageUrl': 'assets/images/suitcase.png',
  },
  {
  'id': '7',
  'category': 'Rashguard',
  'title': 'Rashguard - Tempestal',
  'price': '\$ 45,00',
  'sizes': ['A1', 'A2', 'A3', 'A4'],
  'imageUrl': 'assets/images/rashguards_tempestal.png',
  },
  {
  'id': '8',
  'category': 'Judogi',
  'title': 'Blue Judogi - Mizuno',
  'price': '\$ 1.929,00',
  'sizes': ['A1', 'A2', 'A3', 'A4'],
  'imageUrl': 'assets/images/judogi_mizuno.png',
  },
  {
  'id': '9',
  'category': 'Obi',
  'title': 'Brown Belt - Mizuno',
  'price': '\$ 59,00',
  'sizes': ['1', '2', '3', '4'],
  'imageUrl': 'assets/images/brown_mizuno.png',
  },
  {
  'id': '10',
  'category': 'Accessories',
  'title': 'Sauna Suit - Mizuno',
  'price': '\$ 109,00',
  'sizes': ['A1', 'A2', 'A3', 'A4'],
  'imageUrl': 'assets/images/sauna_suit.png',
  },
];